/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Answers whether the process is up, nothing more.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness — whether dependencies are reachable.
         *
         *     Reports `degraded` while there are no dependencies to check, rather than a bare
         *     `ok`: an unconditional 200 here would make the Cloud Run health gate meaningless
         *     the moment Postgres and Neo4j are wired in at S1/S2.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes server-side and clears the cookies, whatever state the session was in.
         *
         *     Deliberately not behind `get_principal`. A logout that refuses because the session
         *     had already expired would leave a stale cookie in the browser and give the user no
         *     way to clear it — the one moment a strict check makes things less safe, not more.
         *
         *     Revocation is server-side as well as cookie-clearing: deleting the cookie alone
         *     leaves the handle valid, so anyone who captured it keeps a working session.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Challenge */
        post: operations["request_challenge_v1_auth_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Employees
         * @description Everyone in the caller's organisation.
         *
         *     The organisation is never a parameter. It comes from the session, and row-level
         *     security scopes the query — so there is no combination of arguments that returns
         *     another tenant's people.
         */
        get: operations["read_employees_v1_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employees/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_v1_employees_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employees/{user_id}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Employee Identities
         * @description Which accounts are linked to one employee.
         *
         *     Read-only, so there is no rank check: `integration:read` is the ceiling, and an
         *     administrator who may see the organisation's integrations may see which of its people
         *     are attached to them.
         */
        get: operations["read_employee_identities_v1_employees__user_id__identities_get"];
        put?: never;
        /**
         * Create Employee Identity
         * @description Link a provider subject to an employee. **This grants document access.**
         *
         *     Everything about this endpoint follows from that sentence. The permission is the
         *     outer gate; inside, `link_identity` refuses a self-link outright, enforces the rank
         *     ceiling, resolves the target under row-level security, and writes an audit row naming
         *     the actor.
         *
         *     The self-link refusal is not a permission check and cannot be granted away. §17 keeps
         *     roles and ACLs apart — nothing in `Permission` may confer a document read — and an
         *     administrator linking themselves would be exactly that.
         */
        post: operations["create_employee_identity_v1_employees__user_id__identities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/employees/{user_id}/identities/{identity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Employee Identity
         * @description Revoke a linked identity. Effective on the target's next request.
         *
         *     A deactivation rather than a delete, so the row survives for the audit trail. There is
         *     nothing to invalidate: principals are resolved fresh on every request, which is what
         *     makes "immediately" true rather than aspirational.
         */
        delete: operations["delete_employee_identity_v1_employees__user_id__identities__identity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Evidence
         * @description The source span behind one citation, if this caller may read it.
         *
         *     A chunk the caller is not granted is **404, not 403**. A 403 would confirm that the
         *     chunk exists, which turns this endpoint into an oracle: walk ids, read the status
         *     codes, and recover the shape of a tenant's document population without ever being
         *     authorized to read one. `NotFound` is the single answer for never-existed,
         *     another-tenant's, and not-granted-to-you.
         */
        get: operations["read_evidence_v1_evidence__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept
         * @description Join an organisation, and sign in.
         *
         *     No second code is sent. The token reached the invited address and nowhere else, so
         *     holding it already proves the same thing an emailed code would — sending another
         *     would be ceremony, not security.
         *
         *     A welcome does go out, and it is not ceremony. `jutsu_id` below is shown on exactly
         *     one screen, and the console asks for it by name at every subsequent sign-in — so a
         *     closed tab currently costs somebody their identifier and an email to their
         *     administrator. The message carries that, their role and the address to sign in with.
         *     It carries no organisation identifier: the sign-in form does not ask for one.
         */
        post: operations["accept_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Requires `profile:self_read`, which every role holds including a bare Member.
         *
         *     Deliberately the most permissive gate in the catalogue, and the docstring here used
         *     to claim the opposite — that it required `org:read` and refused a Member. It does
         *     not, and it must not: this endpoint is how a client learns which surface it is
         *     allowed to render, so gating it on an admin permission would leave a Member unable
         *     to discover that they are a Member.
         */
        get: operations["read_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Identities
         * @description Which accounts are linked to the caller, and which were revoked.
         *
         *     Held by every role including a bare Member. Seeing what has been connected on your
         *     behalf is not an administrative privilege, and gating it on one would leave the people
         *     with the least power least able to check.
         */
        get: operations["read_my_identities_v1_me_identities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current Organisation
         * @description The signed-in caller's own organisation.
         *
         *     There is deliberately no `{org_id}` variant. An organisation id in a path is an
         *     authorisation input from the client, and the whole architecture refuses those — the
         *     tenant comes from the session, server-side, every time. That also means this route
         *     cannot be used to probe whether another organisation exists.
         */
        get: operations["read_current_organisation_v1_orgs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Stage the registration and send a code. Creates no organisation.
         *
         *     A mismatch between the work address and the claimed domain is answered plainly — both
         *     values came from this request, so saying so discloses nothing — but whether the domain
         *     is already registered is not, and cannot be reached from here at all: that answer is
         *     only produced after someone proves a mailbox at it.
         */
        post: operations["register_v1_orgs_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Verify
         * @description Redeem a registration code and create the organisation.
         *
         *     Separate from `/v1/auth/verify` deliberately. That route documents "the same error for
         *     every rejection" and folds "valid code, but no membership" into it — and a brand-new
         *     registrant is exactly that case, so merging the two would either break its uniformity
         *     or make registration unreachable. Keeping them apart lets each stay absolute:
         *     `expected_purpose` means a sign-in code cannot complete a registration here, and a
         *     registration code cannot open a session there.
         */
        post: operations["register_verify_v1_orgs_register_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptPayload */
        AcceptPayload: {
            /** Full Name */
            full_name: string;
            /** Token */
            token: string;
        };
        /** AcceptResult */
        AcceptResult: {
            /** Destination */
            destination: string;
            /** Jutsu Id */
            jutsu_id: string;
        };
        /**
         * Capabilities
         * @description The caller's own identity and permission set.
         *
         *     `org_id` and `user_id` are opaque UUIDs. They are safe to return to the person they
         *     describe, and they are what the UI uses for its own routing — but they are never
         *     accepted back as an authorisation input, which is why no endpoint takes an org id
         *     from the client.
         */
        Capabilities: {
            /** Jutsu Id */
            jutsu_id: string | null;
            /** Org Id */
            org_id: string;
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
            role: components["schemas"]["Role"];
            /** User Id */
            user_id: string;
        };
        /**
         * ChallengeAccepted
         * @description Identical for every input. Carries no signal about whether the account exists.
         */
        ChallengeAccepted: {
            /**
             * Status
             * @default sent
             */
            status: string;
        };
        /** ChallengeRequest */
        ChallengeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Employee */
        Employee: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Jutsu Id */
            jutsu_id: string | null;
            /** Last Activity At */
            last_activity_at: string | null;
            role: components["schemas"]["Role"] | null;
            /** Status */
            status: string;
        };
        /**
         * EmployeePage
         * @description A page of people, plus the cursor for the next one.
         *
         *     `next_cursor` is opaque and keyset-based rather than a page number. Offset paging over
         *     a table being written to skips and duplicates rows between pages — and this table is
         *     written to exactly when an admin is looking at it, because that is when they invite.
         */
        EmployeePage: {
            /** Items */
            items: components["schemas"]["Employee"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * EvidenceView
         * @description One chunk, with everything a citation needs to render (§12 `Citation`).
         *
         *     `char_start` and `char_end` index the **original** document, while `text` is the
         *     masked body the model was given. That is deliberate and it is the trap CLAUDE.md
         *     records: highlighting the returned text with these offsets mis-highlights the span,
         *     because masking changes lengths. They address the source document, not this string.
         */
        EvidenceView: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Title */
            document_title: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Source System */
            source_system: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvitationAccepted */
        InvitationAccepted: {
            /**
             * Status
             * @default sent
             */
            status: string;
        };
        /** InvitePayload */
        InvitePayload: {
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["Role"];
        };
        /** LinkPayload */
        LinkPayload: {
            source_system: components["schemas"]["SourceSystem"];
            /** Subject */
            subject: string;
        };
        /**
         * MemberCounts
         * @description Headline numbers for the overview.
         *
         *     Computed under the tenant scope, so these are this organisation's rows and nobody
         *     else's — row-level security does the filtering, not a WHERE clause someone has to
         *     remember to write.
         */
        MemberCounts: {
            /** Active */
            active: number;
            /** Admins */
            admins: number;
            /** Deactivated */
            deactivated: number;
            /** Invited */
            invited: number;
            /** Total */
            total: number;
        };
        /** OrganisationProfile */
        OrganisationProfile: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain */
            domain: string | null;
            /** Id */
            id: string;
            members: components["schemas"]["MemberCounts"];
            /** Name */
            name: string;
            /** Size Band */
            size_band: string | null;
            /** Status */
            status: string;
        };
        /**
         * Permission
         * @description What a caller may do. Namespaced `subject:verb` so the set stays readable.
         * @enum {string}
         */
        Permission: "org:read" | "org:update" | "org:delete" | "member:read" | "member:invite" | "member:update" | "member:assign_role" | "integration:read" | "integration:connect" | "integration:revoke" | "audit:read" | "profile:self_read" | "profile:self_update" | "integration:self_manage" | "retrieval:query";
        /** RegisterPayload */
        RegisterPayload: {
            /** Company Domain */
            company_domain: string;
            /** Company Name */
            company_name: string;
            /** Country */
            country?: string | null;
            /** Full Name */
            full_name: string;
            /** Industry */
            industry?: ("consulting" | "technology" | "finance" | "healthcare" | "manufacturing" | "government" | "other") | null;
            /** Job Title */
            job_title: string;
            /** Org Size */
            org_size: string;
            /**
             * Terms Accepted
             * @constant
             */
            terms_accepted: true;
            /**
             * Work Email
             * Format: email
             */
            work_email: string;
        };
        /** RegisterVerifyPayload */
        RegisterVerifyPayload: {
            /** Code */
            code: string;
            /** Token */
            token: string;
        };
        /**
         * RegistrationAccepted
         * @description Deliberately says nothing about what happened.
         *
         *     No organisation id, no JUTSU ID, no "already exists". The next step is in the
         *     recipient's inbox, which is the only channel that proves they control the address.
         */
        RegistrationAccepted: {
            /**
             * Status
             * @default check_your_email
             */
            status: string;
        };
        /** RegistrationComplete */
        RegistrationComplete: {
            /** Destination */
            destination: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "super_admin" | "hr_admin" | "it_admin" | "analyst" | "viewer" | "member";
        /** SourceIdentityPage */
        SourceIdentityPage: {
            /** Items */
            items: components["schemas"]["SourceIdentityView"][];
        };
        /**
         * SourceIdentityView
         * @description One linked identity, as a caller sees it.
         *
         *     `subject` is returned. It is an identifier rather than a secret — the point of the
         *     transparency surface is to say *which* account is linked, and an opaque row that will
         *     not name it answers nothing. It is never a credential; no token is stored anywhere in
         *     this product.
         */
        SourceIdentityView: {
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Linked At
             * Format: date-time
             */
            linked_at: string;
            /** Linked By */
            linked_by: string;
            /** Revoked At */
            revoked_at: string | null;
            source_system: components["schemas"]["SourceSystem"];
            /** Subject */
            subject: string;
        };
        /**
         * SourceSystem
         * @description Every system JUTSU can read from. Read-only, always (§4.8).
         * @enum {string}
         */
        SourceSystem: "local" | "gmail" | "m365" | "slack" | "jira" | "confluence" | "github";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Code */
            code: string;
            /** Token */
            token: string;
        };
        /** VerifyResult */
        VerifyResult: {
            /** Destination */
            destination: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_challenge_v1_auth_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_employees_v1_employees_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_v1_employees_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_employee_identities_v1_employees__user_id__identities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceIdentityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employee_identity_v1_employees__user_id__identities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceIdentityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employee_identity_v1_employees__user_id__identities__identity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                identity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_evidence_v1_evidence__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    read_my_identities_v1_me_identities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceIdentityPage"];
                };
            };
        };
    };
    read_current_organisation_v1_orgs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationProfile"];
                };
            };
        };
    };
    register_v1_orgs_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_verify_v1_orgs_register_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterVerifyPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationComplete"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
