"""The brand mark, loaded once and attached to every branded message.

`assets/jutsu-mark.png` is generated by `apps/web/scripts/make-icons.js` from the same
source artwork the site and the app icons come from, so the mark in an email cannot drift
from the mark on the landing page. It is committed rather than fetched at build time
because the API image is built without the web workspace.

Read once and cached. Every authentication email carries the same eleven kilobytes, and
re-reading the file per send would put disk I/O on the sign-in path for a value that
cannot change while the process lives.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from jutsu_api.email import InlineImage
from jutsu_api.emails.components import LOGO_CID

__all__ = ["brand_mark"]

_MARK = Path(__file__).resolve().parent / "assets" / "jutsu-mark.png"


@lru_cache(maxsize=1)
def brand_mark() -> InlineImage:
    """The 96px mark, composited on white, ready to attach as a related part.

    A missing file is left to raise. The alternative — degrading to a message with a
    broken image — hides a packaging error behind mail that still mostly works, and the
    first person to notice would be a customer looking at a red X where the logo goes.
    """
    return InlineImage(
        cid=LOGO_CID,
        filename="jutsu-mark.png",
        subtype="png",
        data=_MARK.read_bytes(),
    )
