"""Initial schema — spec §8.

Hand-written rather than autogenerated. Autogenerate cannot express `CREATE EXTENSION`,
HNSW index options, RLS policies or `FORCE ROW LEVEL SECURITY`, and silently omitting
any of those would leave a schema that looks right and enforces nothing.

Revision ID: 0001
Revises:
Create Date: 2026-08-19
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql as pg

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 768
RLS_TABLES = ("documents", "chunks", "document_acl")

UUID = pg.UUID(as_uuid=True)
JSONB = pg.JSONB


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # LangGraph checkpoints live apart from domain tables (§8). Created here so the
    # checkpointer has somewhere to write the moment agents land in S8/S13.
    op.execute("CREATE SCHEMA IF NOT EXISTS langgraph")

    source_system = pg.ENUM(
        "local",
        "gmail",
        "m365",
        "slack",
        "jira",
        "confluence",
        "github",
        name="source_system",
        # Created once, explicitly, below. Leaving this True makes create_table
        # emit a second CREATE TYPE and the migration dies on DuplicateObject.
        create_type=False,
    )
    pii_type = pg.ENUM(
        "person",
        "email",
        "phone",
        "address",
        "gov_id",
        "financial",
        name="pii_type",
        create_type=False,
    )
    source_system.create(op.get_bind(), checkfirst=True)
    pii_type.create(op.get_bind(), checkfirst=True)

    # ------------------------------------------------------------------ tenancy
    op.create_table(
        "orgs",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )

    op.create_table(
        "users",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("external_id", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(255)),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("org_id", "external_id", name="uq_users_org_id_external_id"),
    )
    op.create_index("ix_users_org_id_email", "users", ["org_id", "email"])

    op.create_table(
        "user_groups",
        sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("group_external_id", sa.String(255), primary_key=True),
    )

    # ------------------------------------------------------------------ ingestion
    op.create_table(
        "sources",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("system", source_system, nullable=False),
        sa.Column("config_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("last_sync_cursor", sa.Text),
        sa.Column("last_sync_at", sa.DateTime(timezone=True)),
        sa.Column("status", sa.String(32), nullable=False, server_default="idle"),
    )

    op.create_table(
        "documents",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "source_id", UUID, sa.ForeignKey("sources.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("external_id", sa.String(512), nullable=False),
        sa.Column("uri", sa.Text),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("mime", sa.String(128), nullable=False, server_default="text/plain"),
        sa.Column("author_external_id", sa.String(255)),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("acl_hash", sa.String(64), nullable=False),
        sa.Column("body_original", sa.Text, nullable=False),
        sa.Column("body_masked", sa.Text, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True)),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("superseded_by", UUID, sa.ForeignKey("documents.id", ondelete="SET NULL")),
        # §4.14 — the idempotency key. A second seed run must add zero rows.
        sa.UniqueConstraint(
            "org_id", "source_id", "external_id", name="uq_documents_org_source_external"
        ),
        # Target for the composite FK from chunks and document_acl (ADR 0002).
        sa.UniqueConstraint("id", "org_id", name="uq_documents_id_org_id"),
    )
    op.create_index("ix_documents_content_hash", "documents", ["content_hash"])
    op.create_index("ix_documents_org_id", "documents", ["org_id"])

    op.create_table(
        "chunks",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("document_id", UUID, nullable=False),
        sa.Column("org_id", UUID, nullable=False),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        # Offsets index the ORIGINAL document body, not `text` (which is masked).
        sa.Column("char_start", sa.Integer, nullable=False),
        sa.Column("char_end", sa.Integer, nullable=False),
        sa.Column("token_count", sa.Integer, nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        sa.ForeignKeyConstraint(
            ["document_id", "org_id"],
            ["documents.id", "documents.org_id"],
            ondelete="CASCADE",
            name="fk_chunks_document_id_org_id",
        ),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_id_ordinal"),
        sa.CheckConstraint("char_end >= char_start", name="ck_chunks_char_range"),
    )
    op.create_index("ix_chunks_document_id_ordinal", "chunks", ["document_id", "ordinal"])
    # Built on an empty table, where it is instant. Building it after 45k documents
    # takes minutes and blocks writes.
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    op.create_table(
        "document_acl",
        sa.Column("document_id", UUID, primary_key=True),
        sa.Column("principal_type", sa.String(16), primary_key=True),
        sa.Column("principal_id", sa.String(255), primary_key=True),
        sa.Column("org_id", UUID, nullable=False),
        sa.Column("permission", sa.String(16), nullable=False, server_default="read"),
        sa.ForeignKeyConstraint(
            ["document_id", "org_id"],
            ["documents.id", "documents.org_id"],
            ondelete="CASCADE",
            name="fk_document_acl_document_id_org_id",
        ),
        sa.CheckConstraint(
            "principal_type IN ('user', 'group', 'org', 'public')",
            name="ck_document_acl_principal_type",
        ),
        # §4.8 — no write scope is ever requested, so none can be stored.
        sa.CheckConstraint("permission = 'read'", name="ck_document_acl_permission_read_only"),
    )
    op.create_index(
        "ix_document_acl_principal_id_document_id", "document_acl", ["principal_id", "document_id"]
    )

    op.create_table(
        "pii_vault",
        sa.Column("vault_key", sa.String(128), primary_key=True),
        sa.Column(
            "document_id", UUID, sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("pii_type", pii_type, nullable=False),
        sa.Column("ciphertext", sa.LargeBinary, nullable=False),
    )

    # ------------------------------------------------------------------ extraction
    op.create_table(
        "extraction_runs",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("extractor_version", sa.String(64), nullable=False),
        sa.Column("prompt_hash", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("stats_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )

    op.create_table(
        "extraction_claims",
        sa.Column("id", UUID, primary_key=True),
        sa.Column(
            "run_id", UUID, sa.ForeignKey("extraction_runs.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("chunk_id", UUID, sa.ForeignKey("chunks.id", ondelete="CASCADE"), nullable=False),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("claim_type", sa.String(32), nullable=False),
        sa.Column("payload_json", JSONB, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        # §4.4 — re-running supersedes, never overwrites.
        sa.Column(
            "superseded_by", UUID, sa.ForeignKey("extraction_claims.id", ondelete="SET NULL")
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_extraction_claims_confidence_range"
        ),
    )
    op.create_index("ix_extraction_claims_run_id", "extraction_claims", ["run_id"])
    op.create_index("ix_extraction_claims_chunk_id", "extraction_claims", ["chunk_id"])

    op.create_table(
        "resolution_queue",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("entity_kind", sa.String(32), nullable=False),
        sa.Column("payload_json", JSONB, nullable=False),
        sa.Column("candidates_json", JSONB, nullable=False),
        sa.Column("score", sa.Float, nullable=False),
        sa.Column("state", sa.String(32), nullable=False, server_default="pending"),
    )
    op.create_index("ix_resolution_queue_org_id_state", "resolution_queue", ["org_id", "state"])

    # ------------------------------------------------------------------ ops
    op.create_table(
        "jobs",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID, sa.ForeignKey("orgs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("kind", sa.String(64), nullable=False),
        sa.Column("state", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("idempotency_key", sa.String(512), nullable=False, unique=True),
        sa.Column("payload_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True)),
        sa.Column("error", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index("ix_jobs_state_locked_until", "jobs", ["state", "locked_until"])

    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("org_id", UUID, nullable=False),
        sa.Column("actor_id", sa.String(255)),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("resource_type", sa.String(64), nullable=False),
        sa.Column("resource_id", sa.String(255)),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("meta_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )
    op.create_index("ix_audit_log_org_id_ts", "audit_log", ["org_id", "ts"])

    # ------------------------------------------------------------------ evals
    op.create_table(
        "eval_runs",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("org_id", UUID),
        sa.Column("suite", sa.String(64), nullable=False),
        sa.Column("git_sha", sa.String(40)),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("summary_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )

    op.create_table(
        "eval_results",
        sa.Column("id", UUID, primary_key=True),
        sa.Column(
            "run_id", UUID, sa.ForeignKey("eval_runs.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("metric", sa.String(64), nullable=False),
        sa.Column("value", sa.Float, nullable=False),
        sa.Column("passed", sa.Boolean, nullable=False),
        sa.Column("detail_json", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )
    op.create_index("ix_eval_results_run_id_metric", "eval_results", ["run_id", "metric"])

    # ------------------------------------------------------------------ RLS
    #
    # ENABLE alone is not enough. Without FORCE, the policy is skipped for the table
    # owner — and both dev (`jutsu`) and the migration itself connect as the owner, so
    # every local test would pass against an unenforced policy and the leak would only
    # appear in production under a different role.
    #
    # The predicate must yield NULL for an unscoped session so no row qualifies —
    # failing closed is the point. NULLIF is load-bearing: `current_setting(.., true)`
    # returns NULL only while the GUC has never been set in the session. After any
    # set_config, a later transaction sees an EMPTY STRING instead, and ''::uuid
    # raises InvalidTextRepresentation rather than filtering. NULLIF turns both the
    # unset and the reset case back into NULL.
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_org_isolation ON {table} "
            f"USING (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) "
            f"WITH CHECK (org_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)"
        )

    # ------------------------------------------------------------------ app role
    #
    # Migrations run as the owner; the application runs as jutsu_app, which is
    # NOSUPERUSER NOBYPASSRLS so the policies above actually bind to it. A superuser
    # bypasses RLS unconditionally and FORCE does not change that, so connecting the
    # app as the bootstrap role would leave every policy inert.
    #
    # Guarded on existence: the role is created by infrastructure (compose initdb in
    # dev, Terraform in staging and prod), not by this migration, because a role is
    # cluster-wide and its password belongs in Secret Manager.
    op.execute(
        """
        DO $do$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jutsu_app') THEN
            GRANT USAGE ON SCHEMA public TO jutsu_app;
            GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO jutsu_app;
            GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO jutsu_app;
            GRANT USAGE ON SCHEMA langgraph TO jutsu_app;
          END IF;
        END $do$;
        """
    )


def downgrade() -> None:
    """Full reversal. M1 requires migrations to be reversible, and the fingerprint test
    proves upgrade→downgrade→upgrade returns an identical schema."""
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # Reverse dependency order.
    for table in (
        "eval_results",
        "eval_runs",
        "audit_log",
        "jobs",
        "resolution_queue",
        "extraction_claims",
        "extraction_runs",
        "pii_vault",
        "document_acl",
        "chunks",
        "documents",
        "sources",
        "user_groups",
        "users",
        "orgs",
    ):
        op.drop_table(table)

    op.execute("DROP TYPE IF EXISTS pii_type")
    op.execute("DROP TYPE IF EXISTS source_system")
    op.execute("DROP SCHEMA IF EXISTS langgraph CASCADE")
    # The vector extension is intentionally left installed: it is database-wide, may be
    # shared, and dropping it would cascade into anything else using a vector column.
